package com.jsc.hotspot.db.dao;

import com.jsc.hotspot.db.domain.CameraCatInfo;
import com.jsc.hotspot.db.domain.CameraCatInfoExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CameraCatInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    long countByExample(CameraCatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    int deleteByExample(CameraCatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    int insert(CameraCatInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    int insertSelective(CameraCatInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    CameraCatInfo selectOneByExample(CameraCatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    CameraCatInfo selectOneByExampleSelective(@Param("example") CameraCatInfoExample example, @Param("selective") CameraCatInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    List<CameraCatInfo> selectByExampleSelective(@Param("example") CameraCatInfoExample example, @Param("selective") CameraCatInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    List<CameraCatInfo> selectByExample(CameraCatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    CameraCatInfo selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") CameraCatInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    CameraCatInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CameraCatInfo record, @Param("example") CameraCatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CameraCatInfo record, @Param("example") CameraCatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CameraCatInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_cat_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CameraCatInfo record);

    /**
     *
     * 功能描述: 此处是为了获取15天内的上号数量进行展示
     *
     * @param: List<Date> capture_time
     * @return: List<Map>
     * @auther: ww
     * @date: 2019/11/15 0015 10:25
     */
    List<Map> selectCount(List<Date> capture_time);
}