package com.jsc.hotspot.db.dao;

import com.jsc.hotspot.db.domain.CameraCompareResultDAO;
import com.jsc.hotspot.db.domain.CameraCompareResultDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CameraCompareResultDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    long countByExample(CameraCompareResultDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    int deleteByExample(CameraCompareResultDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    int insert(CameraCompareResultDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    int insertSelective(CameraCompareResultDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    CameraCompareResultDAO selectOneByExample(CameraCompareResultDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    CameraCompareResultDAO selectOneByExampleSelective(@Param("example") CameraCompareResultDAOExample example, @Param("selective") CameraCompareResultDAO.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    List<CameraCompareResultDAO> selectByExampleSelective(@Param("example") CameraCompareResultDAOExample example, @Param("selective") CameraCompareResultDAO.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    List<CameraCompareResultDAO> selectByExample(CameraCompareResultDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    CameraCompareResultDAO selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") CameraCompareResultDAO.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    CameraCompareResultDAO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CameraCompareResultDAO record, @Param("example") CameraCompareResultDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CameraCompareResultDAO record, @Param("example") CameraCompareResultDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CameraCompareResultDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CameraCompareResultDAO record);
}