package com.jsc.hotspot.db.dao;

import com.jsc.hotspot.db.domain.HotFrontDeviceDAO;
import com.jsc.hotspot.db.domain.HotFrontDeviceDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotFrontDeviceDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    long countByExample(HotFrontDeviceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int deleteByExample(HotFrontDeviceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long devId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int insert(HotFrontDeviceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int insertSelective(HotFrontDeviceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    HotFrontDeviceDAO selectOneByExample(HotFrontDeviceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    HotFrontDeviceDAO selectOneByExampleSelective(@Param("example") HotFrontDeviceDAOExample example, @Param("selective") HotFrontDeviceDAO.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    List<HotFrontDeviceDAO> selectByExampleSelective(@Param("example") HotFrontDeviceDAOExample example, @Param("selective") HotFrontDeviceDAO.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    List<HotFrontDeviceDAO> selectByExample(HotFrontDeviceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    HotFrontDeviceDAO selectByPrimaryKeySelective(@Param("devId") Long devId, @Param("selective") HotFrontDeviceDAO.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    HotFrontDeviceDAO selectByPrimaryKey(Long devId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HotFrontDeviceDAO record, @Param("example") HotFrontDeviceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HotFrontDeviceDAO record, @Param("example") HotFrontDeviceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HotFrontDeviceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HotFrontDeviceDAO record);
}