package com.jsc.hotspot.db.dao;

import com.jsc.hotspot.db.domain.HotFrontDevice;
import com.jsc.hotspot.db.domain.HotFrontDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotFrontDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    long countByExample(HotFrontDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int deleteByExample(HotFrontDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long devId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int insert(HotFrontDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int insertSelective(HotFrontDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    HotFrontDevice selectOneByExample(HotFrontDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    HotFrontDevice selectOneByExampleSelective(@Param("example") HotFrontDeviceExample example, @Param("selective") HotFrontDevice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    List<HotFrontDevice> selectByExampleSelective(@Param("example") HotFrontDeviceExample example, @Param("selective") HotFrontDevice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    List<HotFrontDevice> selectByExample(HotFrontDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    HotFrontDevice selectByPrimaryKeySelective(@Param("devId") Long devId, @Param("selective") HotFrontDevice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    HotFrontDevice selectByPrimaryKey(Long devId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HotFrontDevice record, @Param("example") HotFrontDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HotFrontDevice record, @Param("example") HotFrontDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HotFrontDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HotFrontDevice record);
}