package com.jsc.hotspot.db.dao;

import com.jsc.hotspot.db.domain.HotNumInfoDAO;
import com.jsc.hotspot.db.domain.HotNumInfoDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotNumInfoDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    long countByExample(HotNumInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int deleteByExample(HotNumInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int insert(HotNumInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int insertSelective(HotNumInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    HotNumInfoDAO selectOneByExample(HotNumInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    HotNumInfoDAO selectOneByExampleSelective(@Param("example") HotNumInfoDAOExample example, @Param("selective") HotNumInfoDAO.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    List<HotNumInfoDAO> selectByExampleSelective(@Param("example") HotNumInfoDAOExample example, @Param("selective") HotNumInfoDAO.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    List<HotNumInfoDAO> selectByExample(HotNumInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    HotNumInfoDAO selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") HotNumInfoDAO.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    HotNumInfoDAO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HotNumInfoDAO record, @Param("example") HotNumInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HotNumInfoDAO record, @Param("example") HotNumInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HotNumInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HotNumInfoDAO record);
}