package com.jsc.hotspot.db.dao;

import com.jsc.hotspot.db.domain.HotNumInfo;
import com.jsc.hotspot.db.domain.HotNumInfoExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HotNumInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    long countByExample(HotNumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int deleteByExample(HotNumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int insert(HotNumInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int insertSelective(HotNumInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    HotNumInfo selectOneByExample(HotNumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    HotNumInfo selectOneByExampleSelective(@Param("example") HotNumInfoExample example, @Param("selective") HotNumInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    List<HotNumInfo> selectByExampleSelective(@Param("example") HotNumInfoExample example, @Param("selective") HotNumInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    List<HotNumInfo> selectByExample(HotNumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    HotNumInfo selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") HotNumInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    HotNumInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HotNumInfo record, @Param("example") HotNumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HotNumInfo record, @Param("example") HotNumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HotNumInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HotNumInfo record);

    /**
     *
     * 功能描述: 此处是为了获取15天内的上号数量进行展示
     *
     * @param: List<Date> capture_time
     * @return: List<Map>
     * @auther: ww
     * @date: 2019/11/15 0015 10:25
     */
    List<Map> selectCount(List<Date> capture_time);
    /**
     *
     * 功能描述: 归属地进行分组统计
     *
     * @param:
     * @return:
     * @auther: ww
     * @date: 2019/11/15 0015 10:26
     */
    List<Map> selectGuiShuDiList();
}