package com.jsc.hotspot.db.dao;

import com.jsc.hotspot.db.domain.HotspotLog;
import com.jsc.hotspot.db.domain.HotspotLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotspotLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    long countByExample(HotspotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    int deleteByExample(HotspotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    int insert(HotspotLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    int insertSelective(HotspotLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    HotspotLog selectOneByExample(HotspotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    HotspotLog selectOneByExampleSelective(@Param("example") HotspotLogExample example, @Param("selective") HotspotLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    List<HotspotLog> selectByExampleSelective(@Param("example") HotspotLogExample example, @Param("selective") HotspotLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    List<HotspotLog> selectByExample(HotspotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    HotspotLog selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") HotspotLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    HotspotLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HotspotLog record, @Param("example") HotspotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HotspotLog record, @Param("example") HotspotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HotspotLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HotspotLog record);
}