package com.jsc.hotspot.db.dao;

import com.jsc.hotspot.db.domain.HotTargetInfo;
import com.jsc.hotspot.db.domain.HotTargetInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface HotTargetInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    long countByExample(HotTargetInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int deleteByExample(HotTargetInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long targetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int insert(HotTargetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int insertSelective(HotTargetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    HotTargetInfo selectOneByExample(HotTargetInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    HotTargetInfo selectOneByExampleSelective(@Param("example") HotTargetInfoExample example, @Param("selective") HotTargetInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    List<HotTargetInfo> selectByExampleSelective(@Param("example") HotTargetInfoExample example, @Param("selective") HotTargetInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    List<HotTargetInfo> selectByExample(HotTargetInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    HotTargetInfo selectByPrimaryKeySelective(@Param("targetId") Long targetId, @Param("selective") HotTargetInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    HotTargetInfo selectByPrimaryKey(Long targetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HotTargetInfo record, @Param("example") HotTargetInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HotTargetInfo record, @Param("example") HotTargetInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HotTargetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HotTargetInfo record);
}