package com.jsc.hotspot.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class CameraCompareResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public CameraCompareResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public CameraCompareResultExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public CameraCompareResultExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        CameraCompareResultExample example = new CameraCompareResultExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public CameraCompareResultExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public CameraCompareResultExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlIsNull() {
            addCriterion("scene_storage_url is null");
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlIsNotNull() {
            addCriterion("scene_storage_url is not null");
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlEqualTo(String value) {
            addCriterion("scene_storage_url =", value, "sceneStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andSceneStorageUrlEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("scene_storage_url = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlNotEqualTo(String value) {
            addCriterion("scene_storage_url <>", value, "sceneStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andSceneStorageUrlNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("scene_storage_url <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlGreaterThan(String value) {
            addCriterion("scene_storage_url >", value, "sceneStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andSceneStorageUrlGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("scene_storage_url > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("scene_storage_url >=", value, "sceneStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andSceneStorageUrlGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("scene_storage_url >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlLessThan(String value) {
            addCriterion("scene_storage_url <", value, "sceneStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andSceneStorageUrlLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("scene_storage_url < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlLessThanOrEqualTo(String value) {
            addCriterion("scene_storage_url <=", value, "sceneStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andSceneStorageUrlLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("scene_storage_url <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlLike(String value) {
            addCriterion("scene_storage_url like", value, "sceneStorageUrl");
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlNotLike(String value) {
            addCriterion("scene_storage_url not like", value, "sceneStorageUrl");
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlIn(List<String> values) {
            addCriterion("scene_storage_url in", values, "sceneStorageUrl");
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlNotIn(List<String> values) {
            addCriterion("scene_storage_url not in", values, "sceneStorageUrl");
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlBetween(String value1, String value2) {
            addCriterion("scene_storage_url between", value1, value2, "sceneStorageUrl");
            return (Criteria) this;
        }

        public Criteria andSceneStorageUrlNotBetween(String value1, String value2) {
            addCriterion("scene_storage_url not between", value1, value2, "sceneStorageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlIsNull() {
            addCriterion("target_face_storage_url is null");
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlIsNotNull() {
            addCriterion("target_face_storage_url is not null");
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlEqualTo(String value) {
            addCriterion("target_face_storage_url =", value, "targetFaceStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetFaceStorageUrlEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_face_storage_url = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlNotEqualTo(String value) {
            addCriterion("target_face_storage_url <>", value, "targetFaceStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetFaceStorageUrlNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_face_storage_url <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlGreaterThan(String value) {
            addCriterion("target_face_storage_url >", value, "targetFaceStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetFaceStorageUrlGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_face_storage_url > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("target_face_storage_url >=", value, "targetFaceStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetFaceStorageUrlGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_face_storage_url >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlLessThan(String value) {
            addCriterion("target_face_storage_url <", value, "targetFaceStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetFaceStorageUrlLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_face_storage_url < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlLessThanOrEqualTo(String value) {
            addCriterion("target_face_storage_url <=", value, "targetFaceStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetFaceStorageUrlLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_face_storage_url <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlLike(String value) {
            addCriterion("target_face_storage_url like", value, "targetFaceStorageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlNotLike(String value) {
            addCriterion("target_face_storage_url not like", value, "targetFaceStorageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlIn(List<String> values) {
            addCriterion("target_face_storage_url in", values, "targetFaceStorageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlNotIn(List<String> values) {
            addCriterion("target_face_storage_url not in", values, "targetFaceStorageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlBetween(String value1, String value2) {
            addCriterion("target_face_storage_url between", value1, value2, "targetFaceStorageUrl");
            return (Criteria) this;
        }

        public Criteria andTargetFaceStorageUrlNotBetween(String value1, String value2) {
            addCriterion("target_face_storage_url not between", value1, value2, "targetFaceStorageUrl");
            return (Criteria) this;
        }

        public Criteria andVideoIdIsNull() {
            addCriterion("video_id is null");
            return (Criteria) this;
        }

        public Criteria andVideoIdIsNotNull() {
            addCriterion("video_id is not null");
            return (Criteria) this;
        }

        public Criteria andVideoIdEqualTo(String value) {
            addCriterion("video_id =", value, "videoId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andVideoIdEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("video_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoIdNotEqualTo(String value) {
            addCriterion("video_id <>", value, "videoId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andVideoIdNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("video_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThan(String value) {
            addCriterion("video_id >", value, "videoId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andVideoIdGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("video_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThanOrEqualTo(String value) {
            addCriterion("video_id >=", value, "videoId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andVideoIdGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("video_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThan(String value) {
            addCriterion("video_id <", value, "videoId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andVideoIdLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("video_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThanOrEqualTo(String value) {
            addCriterion("video_id <=", value, "videoId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andVideoIdLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("video_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVideoIdLike(String value) {
            addCriterion("video_id like", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotLike(String value) {
            addCriterion("video_id not like", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdIn(List<String> values) {
            addCriterion("video_id in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotIn(List<String> values) {
            addCriterion("video_id not in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdBetween(String value1, String value2) {
            addCriterion("video_id between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotBetween(String value1, String value2) {
            addCriterion("video_id not between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andCaptureTimeIsNull() {
            addCriterion("capture_time is null");
            return (Criteria) this;
        }

        public Criteria andCaptureTimeIsNotNull() {
            addCriterion("capture_time is not null");
            return (Criteria) this;
        }

        public Criteria andCaptureTimeEqualTo(LocalDateTime value) {
            addCriterion("capture_time =", value, "captureTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureTimeEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureTimeNotEqualTo(LocalDateTime value) {
            addCriterion("capture_time <>", value, "captureTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureTimeNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureTimeGreaterThan(LocalDateTime value) {
            addCriterion("capture_time >", value, "captureTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureTimeGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("capture_time >=", value, "captureTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureTimeGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureTimeLessThan(LocalDateTime value) {
            addCriterion("capture_time <", value, "captureTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureTimeLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("capture_time <=", value, "captureTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureTimeLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureTimeIn(List<LocalDateTime> values) {
            addCriterion("capture_time in", values, "captureTime");
            return (Criteria) this;
        }

        public Criteria andCaptureTimeNotIn(List<LocalDateTime> values) {
            addCriterion("capture_time not in", values, "captureTime");
            return (Criteria) this;
        }

        public Criteria andCaptureTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("capture_time between", value1, value2, "captureTime");
            return (Criteria) this;
        }

        public Criteria andCaptureTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("capture_time not between", value1, value2, "captureTime");
            return (Criteria) this;
        }

        public Criteria andDevIdIsNull() {
            addCriterion("dev_id is null");
            return (Criteria) this;
        }

        public Criteria andDevIdIsNotNull() {
            addCriterion("dev_id is not null");
            return (Criteria) this;
        }

        public Criteria andDevIdEqualTo(Long value) {
            addCriterion("dev_id =", value, "devId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andDevIdEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("dev_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDevIdNotEqualTo(Long value) {
            addCriterion("dev_id <>", value, "devId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andDevIdNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("dev_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDevIdGreaterThan(Long value) {
            addCriterion("dev_id >", value, "devId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andDevIdGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("dev_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDevIdGreaterThanOrEqualTo(Long value) {
            addCriterion("dev_id >=", value, "devId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andDevIdGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("dev_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDevIdLessThan(Long value) {
            addCriterion("dev_id <", value, "devId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andDevIdLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("dev_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDevIdLessThanOrEqualTo(Long value) {
            addCriterion("dev_id <=", value, "devId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andDevIdLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("dev_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDevIdIn(List<Long> values) {
            addCriterion("dev_id in", values, "devId");
            return (Criteria) this;
        }

        public Criteria andDevIdNotIn(List<Long> values) {
            addCriterion("dev_id not in", values, "devId");
            return (Criteria) this;
        }

        public Criteria andDevIdBetween(Long value1, Long value2) {
            addCriterion("dev_id between", value1, value2, "devId");
            return (Criteria) this;
        }

        public Criteria andDevIdNotBetween(Long value1, Long value2) {
            addCriterion("dev_id not between", value1, value2, "devId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgIsNull() {
            addCriterion("target_face_img is null");
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgIsNotNull() {
            addCriterion("target_face_img is not null");
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgEqualTo(String value) {
            addCriterion("target_face_img =", value, "targetFaceImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetFaceImgEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_face_img = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgNotEqualTo(String value) {
            addCriterion("target_face_img <>", value, "targetFaceImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetFaceImgNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_face_img <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgGreaterThan(String value) {
            addCriterion("target_face_img >", value, "targetFaceImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetFaceImgGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_face_img > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgGreaterThanOrEqualTo(String value) {
            addCriterion("target_face_img >=", value, "targetFaceImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetFaceImgGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_face_img >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgLessThan(String value) {
            addCriterion("target_face_img <", value, "targetFaceImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetFaceImgLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_face_img < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgLessThanOrEqualTo(String value) {
            addCriterion("target_face_img <=", value, "targetFaceImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetFaceImgLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_face_img <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgLike(String value) {
            addCriterion("target_face_img like", value, "targetFaceImg");
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgNotLike(String value) {
            addCriterion("target_face_img not like", value, "targetFaceImg");
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgIn(List<String> values) {
            addCriterion("target_face_img in", values, "targetFaceImg");
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgNotIn(List<String> values) {
            addCriterion("target_face_img not in", values, "targetFaceImg");
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgBetween(String value1, String value2) {
            addCriterion("target_face_img between", value1, value2, "targetFaceImg");
            return (Criteria) this;
        }

        public Criteria andTargetFaceImgNotBetween(String value1, String value2) {
            addCriterion("target_face_img not between", value1, value2, "targetFaceImg");
            return (Criteria) this;
        }

        public Criteria andCompareScoreIsNull() {
            addCriterion("compare_score is null");
            return (Criteria) this;
        }

        public Criteria andCompareScoreIsNotNull() {
            addCriterion("compare_score is not null");
            return (Criteria) this;
        }

        public Criteria andCompareScoreEqualTo(Double value) {
            addCriterion("compare_score =", value, "compareScore");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCompareScoreEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("compare_score = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompareScoreNotEqualTo(Double value) {
            addCriterion("compare_score <>", value, "compareScore");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCompareScoreNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("compare_score <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompareScoreGreaterThan(Double value) {
            addCriterion("compare_score >", value, "compareScore");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCompareScoreGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("compare_score > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompareScoreGreaterThanOrEqualTo(Double value) {
            addCriterion("compare_score >=", value, "compareScore");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCompareScoreGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("compare_score >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompareScoreLessThan(Double value) {
            addCriterion("compare_score <", value, "compareScore");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCompareScoreLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("compare_score < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompareScoreLessThanOrEqualTo(Double value) {
            addCriterion("compare_score <=", value, "compareScore");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCompareScoreLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("compare_score <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompareScoreIn(List<Double> values) {
            addCriterion("compare_score in", values, "compareScore");
            return (Criteria) this;
        }

        public Criteria andCompareScoreNotIn(List<Double> values) {
            addCriterion("compare_score not in", values, "compareScore");
            return (Criteria) this;
        }

        public Criteria andCompareScoreBetween(Double value1, Double value2) {
            addCriterion("compare_score between", value1, value2, "compareScore");
            return (Criteria) this;
        }

        public Criteria andCompareScoreNotBetween(Double value1, Double value2) {
            addCriterion("compare_score not between", value1, value2, "compareScore");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgIsNull() {
            addCriterion("capture_face_img is null");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgIsNotNull() {
            addCriterion("capture_face_img is not null");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgEqualTo(String value) {
            addCriterion("capture_face_img =", value, "captureFaceImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureFaceImgEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_face_img = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgNotEqualTo(String value) {
            addCriterion("capture_face_img <>", value, "captureFaceImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureFaceImgNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_face_img <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgGreaterThan(String value) {
            addCriterion("capture_face_img >", value, "captureFaceImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureFaceImgGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_face_img > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgGreaterThanOrEqualTo(String value) {
            addCriterion("capture_face_img >=", value, "captureFaceImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureFaceImgGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_face_img >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgLessThan(String value) {
            addCriterion("capture_face_img <", value, "captureFaceImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureFaceImgLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_face_img < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgLessThanOrEqualTo(String value) {
            addCriterion("capture_face_img <=", value, "captureFaceImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureFaceImgLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_face_img <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgLike(String value) {
            addCriterion("capture_face_img like", value, "captureFaceImg");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgNotLike(String value) {
            addCriterion("capture_face_img not like", value, "captureFaceImg");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgIn(List<String> values) {
            addCriterion("capture_face_img in", values, "captureFaceImg");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgNotIn(List<String> values) {
            addCriterion("capture_face_img not in", values, "captureFaceImg");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgBetween(String value1, String value2) {
            addCriterion("capture_face_img between", value1, value2, "captureFaceImg");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceImgNotBetween(String value1, String value2) {
            addCriterion("capture_face_img not between", value1, value2, "captureFaceImg");
            return (Criteria) this;
        }

        public Criteria andLibraryNameIsNull() {
            addCriterion("library_name is null");
            return (Criteria) this;
        }

        public Criteria andLibraryNameIsNotNull() {
            addCriterion("library_name is not null");
            return (Criteria) this;
        }

        public Criteria andLibraryNameEqualTo(Byte value) {
            addCriterion("library_name =", value, "libraryName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andLibraryNameEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("library_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLibraryNameNotEqualTo(Byte value) {
            addCriterion("library_name <>", value, "libraryName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andLibraryNameNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("library_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLibraryNameGreaterThan(Byte value) {
            addCriterion("library_name >", value, "libraryName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andLibraryNameGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("library_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLibraryNameGreaterThanOrEqualTo(Byte value) {
            addCriterion("library_name >=", value, "libraryName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andLibraryNameGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("library_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLibraryNameLessThan(Byte value) {
            addCriterion("library_name <", value, "libraryName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andLibraryNameLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("library_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLibraryNameLessThanOrEqualTo(Byte value) {
            addCriterion("library_name <=", value, "libraryName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andLibraryNameLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("library_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLibraryNameIn(List<Byte> values) {
            addCriterion("library_name in", values, "libraryName");
            return (Criteria) this;
        }

        public Criteria andLibraryNameNotIn(List<Byte> values) {
            addCriterion("library_name not in", values, "libraryName");
            return (Criteria) this;
        }

        public Criteria andLibraryNameBetween(Byte value1, Byte value2) {
            addCriterion("library_name between", value1, value2, "libraryName");
            return (Criteria) this;
        }

        public Criteria andLibraryNameNotBetween(Byte value1, Byte value2) {
            addCriterion("library_name not between", value1, value2, "libraryName");
            return (Criteria) this;
        }

        public Criteria andDevIpIsNull() {
            addCriterion("dev_ip is null");
            return (Criteria) this;
        }

        public Criteria andDevIpIsNotNull() {
            addCriterion("dev_ip is not null");
            return (Criteria) this;
        }

        public Criteria andDevIpEqualTo(String value) {
            addCriterion("dev_ip =", value, "devIp");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andDevIpEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("dev_ip = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDevIpNotEqualTo(String value) {
            addCriterion("dev_ip <>", value, "devIp");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andDevIpNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("dev_ip <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDevIpGreaterThan(String value) {
            addCriterion("dev_ip >", value, "devIp");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andDevIpGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("dev_ip > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDevIpGreaterThanOrEqualTo(String value) {
            addCriterion("dev_ip >=", value, "devIp");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andDevIpGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("dev_ip >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDevIpLessThan(String value) {
            addCriterion("dev_ip <", value, "devIp");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andDevIpLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("dev_ip < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDevIpLessThanOrEqualTo(String value) {
            addCriterion("dev_ip <=", value, "devIp");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andDevIpLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("dev_ip <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDevIpLike(String value) {
            addCriterion("dev_ip like", value, "devIp");
            return (Criteria) this;
        }

        public Criteria andDevIpNotLike(String value) {
            addCriterion("dev_ip not like", value, "devIp");
            return (Criteria) this;
        }

        public Criteria andDevIpIn(List<String> values) {
            addCriterion("dev_ip in", values, "devIp");
            return (Criteria) this;
        }

        public Criteria andDevIpNotIn(List<String> values) {
            addCriterion("dev_ip not in", values, "devIp");
            return (Criteria) this;
        }

        public Criteria andDevIpBetween(String value1, String value2) {
            addCriterion("dev_ip between", value1, value2, "devIp");
            return (Criteria) this;
        }

        public Criteria andDevIpNotBetween(String value1, String value2) {
            addCriterion("dev_ip not between", value1, value2, "devIp");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlIsNull() {
            addCriterion("capture_face_storage_url is null");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlIsNotNull() {
            addCriterion("capture_face_storage_url is not null");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlEqualTo(String value) {
            addCriterion("capture_face_storage_url =", value, "captureFaceStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureFaceStorageUrlEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_face_storage_url = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlNotEqualTo(String value) {
            addCriterion("capture_face_storage_url <>", value, "captureFaceStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureFaceStorageUrlNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_face_storage_url <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlGreaterThan(String value) {
            addCriterion("capture_face_storage_url >", value, "captureFaceStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureFaceStorageUrlGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_face_storage_url > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("capture_face_storage_url >=", value, "captureFaceStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureFaceStorageUrlGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_face_storage_url >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlLessThan(String value) {
            addCriterion("capture_face_storage_url <", value, "captureFaceStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureFaceStorageUrlLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_face_storage_url < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlLessThanOrEqualTo(String value) {
            addCriterion("capture_face_storage_url <=", value, "captureFaceStorageUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andCaptureFaceStorageUrlLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("capture_face_storage_url <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlLike(String value) {
            addCriterion("capture_face_storage_url like", value, "captureFaceStorageUrl");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlNotLike(String value) {
            addCriterion("capture_face_storage_url not like", value, "captureFaceStorageUrl");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlIn(List<String> values) {
            addCriterion("capture_face_storage_url in", values, "captureFaceStorageUrl");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlNotIn(List<String> values) {
            addCriterion("capture_face_storage_url not in", values, "captureFaceStorageUrl");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlBetween(String value1, String value2) {
            addCriterion("capture_face_storage_url between", value1, value2, "captureFaceStorageUrl");
            return (Criteria) this;
        }

        public Criteria andCaptureFaceStorageUrlNotBetween(String value1, String value2) {
            addCriterion("capture_face_storage_url not between", value1, value2, "captureFaceStorageUrl");
            return (Criteria) this;
        }

        public Criteria andSceneImgIsNull() {
            addCriterion("scene_img is null");
            return (Criteria) this;
        }

        public Criteria andSceneImgIsNotNull() {
            addCriterion("scene_img is not null");
            return (Criteria) this;
        }

        public Criteria andSceneImgEqualTo(String value) {
            addCriterion("scene_img =", value, "sceneImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andSceneImgEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("scene_img = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSceneImgNotEqualTo(String value) {
            addCriterion("scene_img <>", value, "sceneImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andSceneImgNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("scene_img <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSceneImgGreaterThan(String value) {
            addCriterion("scene_img >", value, "sceneImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andSceneImgGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("scene_img > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSceneImgGreaterThanOrEqualTo(String value) {
            addCriterion("scene_img >=", value, "sceneImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andSceneImgGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("scene_img >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSceneImgLessThan(String value) {
            addCriterion("scene_img <", value, "sceneImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andSceneImgLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("scene_img < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSceneImgLessThanOrEqualTo(String value) {
            addCriterion("scene_img <=", value, "sceneImg");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andSceneImgLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("scene_img <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSceneImgLike(String value) {
            addCriterion("scene_img like", value, "sceneImg");
            return (Criteria) this;
        }

        public Criteria andSceneImgNotLike(String value) {
            addCriterion("scene_img not like", value, "sceneImg");
            return (Criteria) this;
        }

        public Criteria andSceneImgIn(List<String> values) {
            addCriterion("scene_img in", values, "sceneImg");
            return (Criteria) this;
        }

        public Criteria andSceneImgNotIn(List<String> values) {
            addCriterion("scene_img not in", values, "sceneImg");
            return (Criteria) this;
        }

        public Criteria andSceneImgBetween(String value1, String value2) {
            addCriterion("scene_img between", value1, value2, "sceneImg");
            return (Criteria) this;
        }

        public Criteria andSceneImgNotBetween(String value1, String value2) {
            addCriterion("scene_img not between", value1, value2, "sceneImg");
            return (Criteria) this;
        }

        public Criteria andTargetNameIsNull() {
            addCriterion("target_name is null");
            return (Criteria) this;
        }

        public Criteria andTargetNameIsNotNull() {
            addCriterion("target_name is not null");
            return (Criteria) this;
        }

        public Criteria andTargetNameEqualTo(String value) {
            addCriterion("target_name =", value, "targetName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetNameEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetNameNotEqualTo(String value) {
            addCriterion("target_name <>", value, "targetName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetNameNotEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetNameGreaterThan(String value) {
            addCriterion("target_name >", value, "targetName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetNameGreaterThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetNameGreaterThanOrEqualTo(String value) {
            addCriterion("target_name >=", value, "targetName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetNameGreaterThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetNameLessThan(String value) {
            addCriterion("target_name <", value, "targetName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetNameLessThanColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetNameLessThanOrEqualTo(String value) {
            addCriterion("target_name <=", value, "targetName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria andTargetNameLessThanOrEqualToColumn(CameraCompareResult.Column column) {
            addCriterion(new StringBuilder("target_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetNameLike(String value) {
            addCriterion("target_name like", value, "targetName");
            return (Criteria) this;
        }

        public Criteria andTargetNameNotLike(String value) {
            addCriterion("target_name not like", value, "targetName");
            return (Criteria) this;
        }

        public Criteria andTargetNameIn(List<String> values) {
            addCriterion("target_name in", values, "targetName");
            return (Criteria) this;
        }

        public Criteria andTargetNameNotIn(List<String> values) {
            addCriterion("target_name not in", values, "targetName");
            return (Criteria) this;
        }

        public Criteria andTargetNameBetween(String value1, String value2) {
            addCriterion("target_name between", value1, value2, "targetName");
            return (Criteria) this;
        }

        public Criteria andTargetNameNotBetween(String value1, String value2) {
            addCriterion("target_name not between", value1, value2, "targetName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table camera_compare_result
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        private CameraCompareResultExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        protected Criteria(CameraCompareResultExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public CameraCompareResultExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table camera_compare_result
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table camera_compare_result
         *
         * @mbg.generated
         */
        void example(com.jsc.hotspot.db.domain.CameraCompareResultExample example);
    }
}