package com.jsc.hotspot.db.domain;

import com.alibaba.fastjson.JSONObject;
import java.util.ArrayList;
import java.util.Arrays;

public class RelatedNumResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_num_result.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_num_result.target_name
     *
     * @mbg.generated
     */
    private String targetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_num_result.related_result
     *
     * @mbg.generated
     */
    private JSONObject relatedResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_num_result.capture_num
     *
     * @mbg.generated
     */
    private Integer captureNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column related_num_result.target_face
     *
     * @mbg.generated
     */
    private String targetFace;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_num_result.id
     *
     * @return the value of related_num_result.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_num_result.id
     *
     * @param id the value for related_num_result.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_num_result.target_name
     *
     * @return the value of related_num_result.target_name
     *
     * @mbg.generated
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_num_result.target_name
     *
     * @param targetName the value for related_num_result.target_name
     *
     * @mbg.generated
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_num_result.related_result
     *
     * @return the value of related_num_result.related_result
     *
     * @mbg.generated
     */
    public JSONObject getRelatedResult() {
        return relatedResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_num_result.related_result
     *
     * @param relatedResult the value for related_num_result.related_result
     *
     * @mbg.generated
     */
    public void setRelatedResult(JSONObject relatedResult) {
        this.relatedResult = relatedResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_num_result.capture_num
     *
     * @return the value of related_num_result.capture_num
     *
     * @mbg.generated
     */
    public Integer getCaptureNum() {
        return captureNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_num_result.capture_num
     *
     * @param captureNum the value for related_num_result.capture_num
     *
     * @mbg.generated
     */
    public void setCaptureNum(Integer captureNum) {
        this.captureNum = captureNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column related_num_result.target_face
     *
     * @return the value of related_num_result.target_face
     *
     * @mbg.generated
     */
    public String getTargetFace() {
        return targetFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column related_num_result.target_face
     *
     * @param targetFace the value for related_num_result.target_face
     *
     * @mbg.generated
     */
    public void setTargetFace(String targetFace) {
        this.targetFace = targetFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table related_num_result
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", targetName=").append(targetName);
        sb.append(", relatedResult=").append(relatedResult);
        sb.append(", captureNum=").append(captureNum);
        sb.append(", targetFace=").append(targetFace);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table related_num_result
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RelatedNumResult other = (RelatedNumResult) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTargetName() == null ? other.getTargetName() == null : this.getTargetName().equals(other.getTargetName()))
            && (this.getRelatedResult() == null ? other.getRelatedResult() == null : this.getRelatedResult().equals(other.getRelatedResult()))
            && (this.getCaptureNum() == null ? other.getCaptureNum() == null : this.getCaptureNum().equals(other.getCaptureNum()))
            && (this.getTargetFace() == null ? other.getTargetFace() == null : this.getTargetFace().equals(other.getTargetFace()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table related_num_result
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTargetName() == null) ? 0 : getTargetName().hashCode());
        result = prime * result + ((getRelatedResult() == null) ? 0 : getRelatedResult().hashCode());
        result = prime * result + ((getCaptureNum() == null) ? 0 : getCaptureNum().hashCode());
        result = prime * result + ((getTargetFace() == null) ? 0 : getTargetFace().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table related_num_result
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        targetName("target_name", "targetName", "VARCHAR", false),
        relatedResult("related_result", "relatedResult", "CHAR", false),
        captureNum("capture_num", "captureNum", "INTEGER", false),
        targetFace("target_face", "targetFace", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table related_num_result
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}